### ISSUE TITLE
即的uvs有问题

### ISSUE THREAD

**Issue by osfans** [takushun-wu/WenJinMincho#1]
https://github.com/takushun-wu/WenJinMincho/blob/59faf02a26fe7babb7311fd766ceac2e451a231a/source/uvs0.txt#L9835

**Comment by takushun-wu** [comment]
感谢您的指出，下版本（v0.504）更正
![image](https://github.com/user-attachments/assets/8a64e70a-38f2-4364-847e-c803cdac2796)

**Comment by osfans** [comment]
又发现了一个。

后来写脚本发现就这两个有冲突：
即≠博 # 5373 E0102;Adobe-Identity0;CID+33763 535A E0108;Adobe-Identity0;CID+33763
杞≠捨 # 675E E0103;Adobe-Identity0;CID+36495 6368 E0102;Adobe-Identity0;CID+36495

**Comment by takushun-wu** [comment]
杞󠄃`675E E0103`（应是**⿰木已**）也有问题，感谢指出。发现是在整合兼容扩展汉字与IVD汉字字图时出现的问题。下版本修复（预计一周内发布修复版）。

**Comment by osfans** [comment]
b58ee3105c3ef98d014e2abd48cdf522e9d55b78
